name: HelloWorld
version: 1.0
author: goldhaxx
main: me.goldhaxx.helloworld.Main
description: HelloWorld - goldhaxx's first MineCraft Spigot Plugin

commands:
  hello:
    aliases: [hi]
    description: This is the Hello command!